
services: # Defines the services to be run.
  redis:
    image: redis
    volumes: # Mounts the db_data volume to the /data directory in the Redis container.
      - db_data:/data
  userapi:
    image: macbucheron/user_api:latest
    ports:
      - "3000:3000" #  Maps port 3000 on the host to port 3000 in the container.
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
volumes:
  db_data: {} # A named volume used by the Redis service to persist data.