- hosts: user_api_vm
  # Run commands as root
  become: true
  # Roles to be executed on these hosts
  roles:
    # Install role
    - role: install
      tags: install
    
    # Configure role
    - role: test
      tags: test
