apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc  # Name of the PersistentVolumeClaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Requesting 1Gi of storage
