apiVersion: v1
kind: Service
metadata:
  name: redis-service  # Name of the service
spec:
  selector:
    app: redis  # Selects pods with label 'app: redis'
  ports:
    - protocol: TCP
      port: 6379        # Exposed port on the service
      targetPort: 6379  # Port on the Redis pod