apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: user-api
spec:
  hosts:
    - user-api-service
  http:
    - route:
      - destination:
          host: user-api-service
          subset: v1
        weight: 50
      - destination:
          host: user-api-service
          subset: v2
        weight: 50
