# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

# for each push or PR on branch MAIN
on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    #defining env variable for directory architecture
    env:
      working-directory: ./userapi
      #defining the default running directory

      NODE_VERSION: "18.19.1" # set this to the node version to use

    defaults:
      run:
        working-directory: ./user_api

    strategy:
      matrix:
        node-version: [18.19.1] #specifying used node version

    steps:
      #REDIS install
      - uses: actions/checkout@v4
      - uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: "7.4.1"
      #REDIS test
      - name: Redis test
        run: redis-cli ping
        working-directory: ${{env.working-directory}}
      #NODE install
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: ${{env.working-directory}}
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      #install project dependencies
      - name: Installing Node dependencies
        run: npm install
        working-directory: ${{env.working-directory}}
      #run test script to check if the build in working
      - name: Running tests
        run: npm test
        working-directory: ${{env.working-directory}}
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ./userapi
