name: Node.js CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      working-directory: ./user_api
      NODE_VERSION: "18.19.1"

    defaults:
      run:
        working-directory: ./user_api

    steps:
      - uses: actions/checkout@v3

      - uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: "6.x"

      - name: Redis test
        run: redis-cli ping

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          cache-dependency-path: ${{env.working-directory}}
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      #install project dependencies
      - name: Installing Node dependencies
        run: npm install
        working-directory: ${{env.working-directory}}

      #run test script to check if the build in working
      - name: Running tests
        run: npm test
        working-directory: ${{env.working-directory}}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ./userapi
