name: Node.js CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Run tests # name of the job
    runs-on: ubuntu-latest # operating system to run the job on
    env:
      working-directory: ./user_api #set the working directory
      NODE_VERSION: "18.19.1" #node version to use
      REDIS_VERSION: "6.x" #redis version to use

    defaults:
      run:
        working-directory: ${{env.working-directory}} #set the default working directory

    steps:
      #checkout the code
      - uses: actions/checkout@v4

      #setup redis
      - uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: ${{ env.REDIS_VERSION }}

      #check if redis is running
      - name: Redis test
        run: redis-cli ping

      #setup node.js
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: ${{env.working-directory}}
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      #install project dependencies
      - name: Installing Node dependencies
        run: npm install
        working-directory: ${{env.working-directory}}

      #run test script to check if the build in working
      - name: Running tests
        run: npm test
        working-directory: ${{env.working-directory}}

