name: User API CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Test for User API and Redis functionnement # name of the job
    runs-on: ${( matrix.os )} # operating system to run the job on
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] # operating system to run the job on
    env:
      working-directory: ./user_api #set the working directory
      NODE_VERSION: "18.19.1" #node version to use
      REDIS_VERSION: "6.x" #redis version to use

    defaults:
      run:
        working-directory: ${{env.working-directory}} #set the default working directory

    steps:
      #checkout the code
      - name: Checkout the code
        uses: actions/checkout@v4

      #setup redis
      - name: Setup Redis ${{ env.REDIS_VERSION }}
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: ${{ env.REDIS_VERSION }}

      #check if redis is running
      - name: Check if Redis is running 
        run: redis-cli ping

      #setup node.js
      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: ${{env.working-directory}}
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      #install project dependencies
      - name: Install Node dependencies
        run: npm install
        working-directory: ${{env.working-directory}}

      #run test script to check if the build in working
      - name: Running the User API tests
        run: npm test
        working-directory: ${{env.working-directory}}

