name: User API CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    strategy: # Define the matrix for the job
      matrix: # We will get 2 jobs : 2 OS * 1 Node.js version * 1 Redis version
        os: [ubuntu-latest, macos-latest]  # All the OS to run the job
        node_version: ["18.19.1"]  # all the Node.js version
        redis_version: ["6.x"]  # all the Redis version

    name: User API on ${{matrix.os}} using NodeJS ${{matrix.node_version}} and Redis ${{matrix.redis_version}} # name of the job
    runs-on: ${{ matrix.os }} 
    env:
      working-directory: ./user_api #set the working directory

    defaults:
      run:
        working-directory: ${{env.working-directory}} #set the default working directory

    steps:
      #checkout the code
      - name: Checkout the code
        uses: actions/checkout@v4

      #setup redis
      - name: Setup Redis ${{ matrix.redis_version }}
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: ${{ matrix.redis_version }}

      #check if redis is running
      - name: Check if Redis is running
        run: redis-cli ping

      #setup node.js
      - name: Setup Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: ${{env.working-directory}}
          node-version: ${{ matrix.node_version }}
          cache: "npm"

      #install project dependencies
      - name: Install Node dependencies
        run: npm install
        working-directory: ${{env.working-directory}}

      #run test script to check if the build in working
      - name: Running the User API tests
        run: npm test
        working-directory: ${{env.working-directory}}
