name: Docker Hub Publisher

on:
  push:
    branches: ["main"]
    paths:
      - 'user_api_Azure/**'
      - '.github/workflows/DockerHub_Publisher.yml'

env:
  working-directory: ./user_api # Set the working directory

jobs:
  docker_push: # This job pushes the Docker image to Docker Hub.
    name: Push the Docker image to Docker Hub

    runs-on: ubuntu-latest

    steps:

      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3


      # Step 2: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      # Step 4: Build and push the Docker image to Docker Hub
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.working-directory }}
          file: ${{ env.working-directory }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/user_api:latest